"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.plural_rules = void 0;
const regex_1 = require("../regex");
exports.plural_rules = [
    // do not replace if its already a plural word
    [regex_1.regex.plural.men],
    [regex_1.regex.plural.people],
    [regex_1.regex.plural.children],
    [regex_1.regex.plural.tia],
    [regex_1.regex.plural.analyses],
    [regex_1.regex.plural.hives],
    [regex_1.regex.plural.curves],
    [regex_1.regex.plural.lrves],
    [regex_1.regex.plural.foves],
    [regex_1.regex.plural.aeiouyies],
    [regex_1.regex.plural.series],
    [regex_1.regex.plural.movies],
    [regex_1.regex.plural.xes],
    [regex_1.regex.plural.mice],
    [regex_1.regex.plural.buses],
    [regex_1.regex.plural.oes],
    [regex_1.regex.plural.shoes],
    [regex_1.regex.plural.crises],
    [regex_1.regex.plural.octopi],
    [regex_1.regex.plural.aliases],
    [regex_1.regex.plural.summonses],
    [regex_1.regex.plural.oxen],
    [regex_1.regex.plural.matrices],
    [regex_1.regex.plural.feet],
    [regex_1.regex.plural.teeth],
    [regex_1.regex.plural.geese],
    [regex_1.regex.plural.quizzes],
    [regex_1.regex.plural.whereases],
    [regex_1.regex.plural.criteria],
    [regex_1.regex.plural.genera],
    // original rule
    [regex_1.regex.singular.man, '$1en'],
    [regex_1.regex.singular.person, '$1ople'],
    [regex_1.regex.singular.child, '$1ren'],
    [regex_1.regex.singular.ox, '$1en'],
    [regex_1.regex.singular.axis, '$1es'],
    [regex_1.regex.singular.octopus, '$1i'],
    [regex_1.regex.singular.alias, '$1es'],
    [regex_1.regex.singular.summons, '$1es'],
    [regex_1.regex.singular.bus, '$1ses'],
    [regex_1.regex.singular.buffalo, '$1oes'],
    [regex_1.regex.singular.tium, '$1a'],
    [regex_1.regex.singular.sis, 'ses'],
    [regex_1.regex.singular.ffe, '$1$2ves'],
    [regex_1.regex.singular.hive, '$1ves'],
    [regex_1.regex.singular.aeiouyy, '$1ies'],
    [regex_1.regex.singular.matrix, '$1ices'],
    [regex_1.regex.singular.vertex, '$1ices'],
    [regex_1.regex.singular.x, '$1es'],
    [regex_1.regex.singular.mouse, '$1ice'],
    [regex_1.regex.singular.foot, 'feet'],
    [regex_1.regex.singular.tooth, 'teeth'],
    [regex_1.regex.singular.goose, 'geese'],
    [regex_1.regex.singular.quiz, '$1zes'],
    [regex_1.regex.singular.whereas, '$1es'],
    [regex_1.regex.singular.criterion, '$1a'],
    [regex_1.regex.singular.genus, 'genera'],
    [regex_1.regex.singular.s, 's'],
    [regex_1.regex.singular.common, 's'],
];
exports.default = exports.plural_rules;
//# sourceMappingURL=plural_rules.js.map