import pluralize from '../pluralize';
import singularize from '../singularize';
import inflect from '../inflect';
import camelize from '../camelize';
import underscore from '../underscore';
import humanize from '../humanize';
import capitalize from '../capitalize';
import dasherize from '../dasherize';
import titleize from '../titleize';
import demodulize from '../demodulize';
import tableize from '../tableize';
import kebabize from '../kebabize';
import classify from '../classify';
import foreign_key from '../foreign_key';
import ordinalize from '../ordinalize';
export declare const inflector: {
    pluralize: typeof pluralize;
    singularize: typeof singularize;
    inflect: typeof inflect;
    camelize: typeof camelize;
    underscore: typeof underscore;
    humanize: typeof humanize;
    capitalize: typeof capitalize;
    dasherize: typeof dasherize;
    titleize: typeof titleize;
    demodulize: typeof demodulize;
    tableize: typeof tableize;
    kebabize: typeof kebabize;
    classify: typeof classify;
    foreign_key: typeof foreign_key;
    ordinalize: typeof ordinalize;
};
export default inflector;
